name: Payments 7d Snapshot
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: OK
        run: echo "workflow file is valid"
